{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app: backend
spec:
  replicas: {{ .Values.backend.replica.count }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: nodejs
          image: {{ .Values.backend.image | required "Backend image empty" }}
          imagePullPolicy: {{ .Values.backend.pullPolicy }}
          args:
            - "node"
            - "--enable-source-maps"
            - "dist/start.js"
            - "http"
          envFrom:
            - secretRef:
                name: app-env
          resources: {{ toYaml .Values.backend.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
{{/*          startupProbe:*/}}
{{/*            initialDelaySeconds: 5*/}}
{{/*            timeoutSeconds: 10*/}}
{{/*            failureThreshold: 5*/}}
{{/*            httpGet:*/}}
{{/*              path: "/probe/alive"*/}}
{{/*              port: 8000*/}}
{{/*          livenessProbe:*/}}
{{/*            timeoutSeconds: 10*/}}
{{/*            httpGet:*/}}
{{/*              path: "/probe/alive"*/}}
{{/*              port: 8000*/}}
{{/*          readinessProbe:*/}}
{{/*            timeoutSeconds: 10*/}}
{{/*            httpGet:*/}}
{{/*              path: "/probe/ready"*/}}
{{/*              port: 8000*/}}
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
      appProtocol: http
{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-frontend-api
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/user-api/$2"
    {{- if .Values.ingress.annotations }}
    {{ toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  rules:
    - host: {{ required "Ingress host must be set" .Values.ingress.host | quote }}
      http:
        paths:
          - path: "/api(/|$)(.*)"
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend
                port:
                  name: http
{{- end }}
{{- if .Values.ingressAdmin.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-frontend-admin-api
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/admin-api/$2"
    {{- if .Values.ingressAdmin.annotations }}
    {{ toYaml .Values.ingressAdmin.annotations | nindent 4 }}
    {{- end }}
spec:
  rules:
    - host: {{ required "Ingress host must be set" .Values.ingressAdmin.host | quote }}
      http:
        paths:
          - path: "/api(/|$)(.*)"
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend
                port:
                  name: http
{{- end }}
{{- end }}
