{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: "redis:7-bullseye"
          imagePullPolicy: IfNotPresent
          resources: {{ toYaml .Values.redis.resources | nindent 12 }}
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
      protocol: TCP
      appProtocol: redis
{{- end }}
