apiVersion: v1
kind: Secret
metadata:
  name: app-env
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config.env }}
  {{ $k }}: {{ $v | b64enc | quote }}
  {{- end }}
